In [6]:
import pandas as pd
import import_data
import run_model
import extract_features
import export_data

In [18]:
def prep_features(features, targets):
    # Training test split, normalize
    from sklearn.preprocessing import StandardScaler
    from sklearn.model_selection import train_test_split

    # Remove features
    features.drop(["Id"], axis=1)

    # Fill NA
    #features.fillna()

    X_train, X_test, y_train, y_test = train_test_split(features, targets, train_size=0.8, random_state=42)

    display(X_train)

    # Normalize
    scaler = StandardScaler().fit(X_train)
    X_train_scaled = pd.DataFrame(scaler.transform(X_train), index=X_train.select_dtypes(include=[np.number]), columns=X_train.columns.values)
    X_test_scaled = pd.DataFrame(scaler.transform(X_test), index=X_test.select_dtypes(include=[np.number]), columns=X_test.columns.values)
    return X_train_scaled, y_train, X_test_scaled, y_test

In [19]:
def execute_model(X_train, y_train, X_test, y_test):
    from sklearn.ensemble import RandomForestRegressor
    rf = RandomForestRegressor(n_estimators=500, oob_score=True, random_state=0)
    rf.fit(X_train, y_train)

    from sklearn.metrics import r2_score
    from scipy.stats import spearmanr, pearsonr
    predicted_train = rf.predict(X_train)
    predicted_test = rf.predict(X_test)
    test_score = r2_score(y_test, predicted_test)
    spearman = spearmanr(y_test, predicted_test)
    pearson = pearsonr(y_test, predicted_test)

    print('Out-of-bag R-2 score estimate: {}'.format(rf.oob_score_))
    print('Test data R-2 score: {}'.format(test_score))
    print('Test data Spearman correlation: {}'.format(spearman[0]))
    print('Test data Pearson correlation: {}'.format(pearson[0]))

In [20]:
def main(path_training, path_test, training_test_seed=None, output_path = r"./output"):
    """Processes data, predicts housing prices, saves predictions.

    Args:
        path_training  (str): Path to training data.
        path_test (str): Path to test data.
        training_test_seed (int, optional): Random seed for internal training/test split.
        output_path ( str): Location to save predicitions

    Returns:
        None
    """


    training_df = import_data.process_data(path_training)
    features = pd.get_dummies(training_df)
    with pd.option_context('display.max_rows', 5, 'display.max_columns', None):
        display(features)
    y = features['SalePrice']
    X_train, y_train, X_test, y_test = prep_features(features, y)
    execute_model(X_train, y_train, X_test, y_test)

In [24]:
path_training =  r'../data/train.csv'
training_df = import_data.process_data(path_training)

In [35]:
df = training_df.drop(['Id'], axis=1)
#display(df)
#display(df.fillna(0))
df.astype("")
x = pd.get_dummies(df)
display(x)

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,1,0,0,0,0,1,0
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,1,0,0,0,0,1,0
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,0,0,1,0,0,0,0,1,0
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,0,0,1,1,0,0,0,0,0
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,0,0,0,1,0,0,0,0,1,0
5,50,85.0,14115,5,5,1993,1995,0.0,732,0,...,0,0,0,1,0,0,0,0,1,0
6,20,75.0,10084,8,5,2004,2005,186.0,1369,0,...,0,0,0,1,0,0,0,0,1,0
7,60,NaN,10382,7,6,1973,1973,240.0,859,32,...,0,0,0,1,0,0,0,0,1,0
8,50,51.0,6120,7,5,1931,1950,0.0,0,0,...,0,0,0,1,1,0,0,0,0,0
9,190,50.0,7420,5,6,1939,1950,0.0,851,0,...,0,0,0,1,0,0,0,0,1,0
10,20,70.0,11200,5,5,1965,1965,0.0,906,0,...,0,0,0,1,0,0,0,0,1,0
11,60,85.0,11924,9,5,2005,2006,286.0,998,0,...,0,1,0,0,0,0,0,0,0,1
12,20,NaN,12968,5,6,1962,1962,0.0,737,0,...,0,0,0,1,0,0,0,0,1,0
13,20,91.0,10652,7,5,2006,2007,306.0,0,0,...,0,1,0,0,0,0,0,0,0,1
14,20,NaN,10920,6,5,1960,1960,212.0,733,0,...,0,0,0,1,0,0,0,0,1,0
15,45,51.0,6120,7,8,1929,2001,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
16,20,NaN,11241,6,7,1970,1970,180.0,578,0,...,0,0,0,1,0,0,0,0,1,0
17,90,72.0,10791,4,5,1967,1967,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
18,20,66.0,13695,5,5,2004,2004,0.0,646,0,...,0,0,0,1,0,0,0,0,1,0
19,20,70.0,7560,5,6,1958,1965,0.0,504,0,...,0,0,0,0,1,0,0,0,0,0
20,60,101.0,14215,8,5,2005,2006,380.0,0,0,...,0,1,0,0,0,0,0,0,0,1
21,45,57.0,7449,7,7,1930,1950,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
22,20,75.0,9742,8,5,2002,2002,281.0,0,0,...,0,0,0,1,0,0,0,0,1,0
23,120,44.0,4224,5,7,1976,1976,0.0,840,0,...,0,0,0,1,0,0,0,0,1,0
24,20,NaN,8246,5,8,1968,2001,0.0,188,668,...,0,0,0,1,0,0,0,0,1,0
25,20,110.0,14230,8,5,2007,2007,640.0,0,0,...,0,0,0,1,0,0,0,0,1,0
26,20,60.0,7200,5,7,1951,2000,0.0,234,486,...,0,0,0,1,0,0,0,0,1,0
27,20,98.0,11478,8,5,2007,2008,200.0,1218,0,...,0,0,0,1,0,0,0,0,1,0
28,20,47.0,16321,5,6,1957,1997,0.0,1277,0,...,0,0,0,1,0,0,0,0,1,0
29,30,60.0,6324,4,6,1927,1950,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1430,60,60.0,21930,5,5,2005,2005,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1431,120,NaN,4928,6,6,1976,1976,0.0,958,0,...,0,0,0,1,0,0,0,0,1,0
1432,30,60.0,10800,4,6,1927,2007,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1433,60,93.0,10261,6,5,2000,2000,318.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1434,20,80.0,17400,5,5,1977,1977,0.0,936,0,...,0,0,0,1,0,0,0,0,1,0
1435,20,80.0,8400,6,9,1962,2005,237.0,0,0,...,0,0,0,0,1,0,0,0,0,0
1436,20,60.0,9000,4,6,1971,1971,0.0,616,0,...,0,0,0,1,0,0,0,0,1,0
1437,20,96.0,12444,8,5,2008,2008,426.0,1336,0,...,0,1,0,0,0,0,0,0,0,1
1438,20,90.0,7407,6,7,1957,1996,0.0,600,0,...,0,0,0,1,0,0,0,0,1,0
1439,60,80.0,11584,7,6,1979,1979,96.0,315,110,...,0,0,0,1,0,0,0,0,1,0
1440,70,79.0,11526,6,7,1922,1994,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1441,120,NaN,4426,6,5,2004,2004,147.0,697,0,...,0,0,0,1,0,0,0,0,1,0
1442,60,85.0,11003,10,5,2008,2008,160.0,765,0,...,0,0,0,1,0,0,0,0,1,0
1443,30,NaN,8854,6,6,1916,1950,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1444,20,63.0,8500,7,5,2004,2004,106.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1445,85,70.0,8400,6,5,1966,1966,0.0,187,627,...,0,0,0,1,0,0,0,0,1,0
1446,20,NaN,26142,5,7,1962,1962,189.0,593,0,...,0,0,0,1,0,0,0,0,1,0
1447,60,80.0,10000,8,5,1995,1996,438.0,1079,0,...,0,0,0,1,0,0,0,0,1,0
1448,50,70.0,11767,4,7,1910,2000,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1449,180,21.0,1533,5,7,1970,1970,0.0,553,0,...,0,0,0,1,1,0,0,0,0,0
1450,90,60.0,9000,5,5,1974,1974,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1451,20,78.0,9262,8,5,2008,2009,194.0,0,0,...,0,1,0,0,0,0,0,0,0,1
1452,180,35.0,3675,5,5,2005,2005,80.0,547,0,...,0,0,0,1,0,0,0,0,1,0
1453,20,90.0,17217,5,5,2006,2006,0.0,0,0,...,0,0,0,1,1,0,0,0,0,0
1454,20,62.0,7500,7,5,2004,2005,0.0,410,0,...,0,0,0,1,0,0,0,0,1,0
1455,60,62.0,7917,6,5,1999,2000,0.0,0,0,...,0,0,0,1,0,0,0,0,1,0
1456,20,85.0,13175,6,6,1978,1988,119.0,790,163,...,0,0,0,1,0,0,0,0,1,0
1457,70,66.0,9042,7,9,1941,2006,0.0,275,0,...,0,0,0,1,0,0,0,0,1,0
1458,20,68.0,9717,5,6,1950,1996,0.0,49,1029,...,0,0,0,1,0,0,0,0,1,0
1459,20,75.0,9937,5,6,1965,1965,0.0,830,290,...,0,0,0,1,0,0,0,0,1,0